# Generated by Django 3.0.2 on 2020-01-14 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_user_is_admin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='birdthdate',
            field=models.DateField(blank=True, null=True),
        ),
    ]
