# Generated by Django 3.0.2 on 2020-01-14 18:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0005_auto_20200114_1752'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='birdthdate',
            new_name='birthdate',
        ),
    ]
